# Generated by Django 4.1.7 on 2023-04-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule_advisor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="class_section",
            field=models.CharField(default="001", max_length=5),
        ),
        migrations.AlterField(
            model_name="class",
            name="subject",
            field=models.CharField(default="", max_length=10),
        ),
    ]
