# Generated by Django 4.1.7 on 2023-04-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule_advisor", "0002_alter_class_class_section_alter_class_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="units",
            field=models.CharField(default="3", max_length=10),
        ),
    ]
