# Generated by Django 4.1.7 on 2023-04-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule_advisor", "0003_alter_class_units"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="catalog_number",
            field=models.CharField(default="0000", max_length=10),
        ),
        migrations.AlterField(
            model_name="class",
            name="class_section",
            field=models.CharField(default="001", max_length=10),
        ),
        migrations.AlterField(
            model_name="class",
            name="component",
            field=models.CharField(default="LEC", max_length=10),
        ),
        migrations.AlterField(
            model_name="class",
            name="semester",
            field=models.CharField(default="", max_length=10),
        ),
    ]
