# Generated by Django 4.1.7 on 2023-04-16 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "schedule_advisor",
            "0004_alter_class_catalog_number_alter_class_class_section_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_admin",
            new_name="is_advisor",
        ),
        migrations.AddField(
            model_name="user",
            name="advisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
