# Generated by Django 4.1.7 on 2023-04-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule_advisor", "0005_rename_is_admin_user_is_advisor_user_advisor"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="approved",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="visible",
            field=models.BooleanField(default=False),
        ),
    ]
