DANCE_EXAMPLE = [
    {
        "index": 1,
        "crse_id": "007179",
        "crse_offer_nbr": 1,
        "strm": "1228",
        "session_code": "1",
        "session_descr": "Regular Academic Session",
        "class_section": "001",
        "location": "MAIN",
        "location_descr": "On Grounds",
        "start_dt": "08/23/2022",
        "end_dt": "12/06/2022",
        "class_stat": "A",
        "campus": "MAIN",
        "campus_descr": "Main Campus",
        "class_nbr": 10948,
        "acad_career": "UGRD",
        "acad_career_descr": "Undergraduate",
        "component": "LEC",
        "subject": "DANC",
        "subject_descr": "Dance",
        "catalog_nbr": "1400",
        "class_type": "E",
        "schedule_print": "Y",
        "acad_group": "CGAS",
        "instruction_mode": "P",
        "instruction_mode_descr": "In Person",
        "acad_org": "DRAM",
        "wait_tot": 0,
        "wait_cap": 199,
        "class_capacity": 20,
        "enrollment_total": 20,
        "enrollment_available": 0,
        "descr": "How Dance Matters",
        "rqmnt_designtn": "",
        "units": "3",
        "combined_section": "N",
        "enrl_stat": "C",
        "enrl_stat_descr": "Closed",
        "topic": "",
        "instructors": [{"name": "Kathryn Schetlick", "email": "kbs2d@virginia.edu"}],
        "section_type": "Lecture",
        "meetings": [
            {
                "days": "TuTh",
                "start_time": "16.00.00.000000-05:00",
                "end_time": "17.15.00.000000-05:00",
                "start_dt": "08/23/2022",
                "end_dt": "12/06/2022",
                "bldg_cd": "DRM",
                "bldg_has_coordinates": True,
                "facility_descr": "Drama Education Bldg 217",
                "room": "217",
                "facility_id": "DRM 217",
                "instructor": "Kathryn Schetlick",
            }
        ],
        "crse_attr": "ASUD,NCLC",
        "crse_attr_value": "ASUD-AIP,ASUD-HP,NCLC-LOWCOST",
        "reserve_caps": [],
    },
    {
        "index": 2,
        "crse_id": "007227",
        "crse_offer_nbr": 1,
        "strm": "1228",
        "session_code": "1",
        "session_descr": "Regular Academic Session",
        "class_section": "001",
        "location": "MAIN",
        "location_descr": "On Grounds",
        "start_dt": "08/23/2022",
        "end_dt": "12/06/2022",
        "class_stat": "A",
        "campus": "MAIN",
        "campus_descr": "Main Campus",
        "class_nbr": 11510,
        "acad_career": "UGRD",
        "acad_career_descr": "Undergraduate",
        "component": "STO",
        "subject": "DANC",
        "subject_descr": "Dance",
        "catalog_nbr": "2220",
        "class_type": "E",
        "schedule_print": "Y",
        "acad_group": "CGAS",
        "instruction_mode": "P",
        "instruction_mode_descr": "In Person",
        "acad_org": "DRAM",
        "wait_tot": 0,
        "wait_cap": 0,
        "class_capacity": 18,
        "enrollment_total": 10,
        "enrollment_available": 8,
        "descr": "Modern/Contemporary I",
        "rqmnt_designtn": "",
        "units": "1",
        "combined_section": "N",
        "enrl_stat": "O",
        "enrl_stat_descr": "Open",
        "topic": "",
        "instructors": [{"name": "Kim Mata", "email": "kbm2n@virginia.edu"}],
        "section_type": "STO",
        "meetings": [
            {
                "days": "TuTh",
                "start_time": "11.00.00.000000-05:00",
                "end_time": "12.15.00.000000-05:00",
                "start_dt": "08/23/2022",
                "end_dt": "12/06/2022",
                "bldg_cd": "MGM",
                "bldg_has_coordinates": True,
                "facility_descr": "Memorial Gymnasium 120-MP",
                "room": "MP1",
                "facility_id": "MGM MP1",
                "instructor": "Kim Mata",
            }
        ],
        "crse_attr": "",
        "crse_attr_value": "",
        "reserve_caps": [],
    },
    {
        "index": 3,
        "crse_id": "007225",
        "crse_offer_nbr": 1,
        "strm": "1228",
        "session_code": "1",
        "session_descr": "Regular Academic Session",
        "class_section": "001",
        "location": "MAIN",
        "location_descr": "On Grounds",
        "start_dt": "08/23/2022",
        "end_dt": "12/06/2022",
        "class_stat": "A",
        "campus": "MAIN",
        "campus_descr": "Main Campus",
        "class_nbr": 10946,
        "acad_career": "UGRD",
        "acad_career_descr": "Undergraduate",
        "component": "STO",
        "subject": "DANC",
        "subject_descr": "Dance",
        "catalog_nbr": "2300",
        "class_type": "E",
        "schedule_print": "Y",
        "acad_group": "CGAS",
        "instruction_mode": "P",
        "instruction_mode_descr": "In Person",
        "acad_org": "DRAM",
        "wait_tot": 0,
        "wait_cap": 199,
        "class_capacity": 12,
        "enrollment_total": 13,
        "enrollment_available": 0,
        "descr": "Dance Improvisation",
        "rqmnt_designtn": "",
        "units": "2 - 3",
        "combined_section": "N",
        "enrl_stat": "C",
        "enrl_stat_descr": "Closed",
        "topic": "",
        "instructors": [{"name": "Kathryn Schetlick", "email": "kbs2d@virginia.edu"}],
        "section_type": "STO",
        "meetings": [
            {
                "days": "TuTh",
                "start_time": "14.00.00.000000-05:00",
                "end_time": "15.15.00.000000-05:00",
                "start_dt": "08/23/2022",
                "end_dt": "12/06/2022",
                "bldg_cd": "MGM",
                "bldg_has_coordinates": True,
                "facility_descr": "Memorial Gymnasium 120-MP",
                "room": "MP1",
                "facility_id": "MGM MP1",
                "instructor": "Kathryn Schetlick",
            }
        ],
        "crse_attr": "NCLC",
        "crse_attr_value": "NCLC-LOWCOST",
        "reserve_caps": [],
    },
    {
        "index": 4,
        "crse_id": "043986",
        "crse_offer_nbr": 1,
        "strm": "1228",
        "session_code": "1",
        "session_descr": "Regular Academic Session",
        "class_section": "001",
        "location": "MAIN",
        "location_descr": "On Grounds",
        "start_dt": "08/23/2022",
        "end_dt": "12/06/2022",
        "class_stat": "A",
        "campus": "MAIN",
        "campus_descr": "Main Campus",
        "class_nbr": 12152,
        "acad_career": "UGRD",
        "acad_career_descr": "Undergraduate",
        "component": "LAB",
        "subject": "DANC",
        "subject_descr": "Dance",
        "catalog_nbr": "2430",
        "class_type": "E",
        "schedule_print": "Y",
        "acad_group": "CGAS",
        "instruction_mode": "P",
        "instruction_mode_descr": "In Person",
        "acad_org": "DRAM",
        "wait_tot": 0,
        "wait_cap": 0,
        "class_capacity": 20,
        "enrollment_total": 14,
        "enrollment_available": 6,
        "descr": "Production Laboratory: Dance",
        "rqmnt_designtn": "",
        "units": "1 - 3",
        "combined_section": "N",
        "enrl_stat": "O",
        "enrl_stat_descr": "Open",
        "topic": "",
        "instructors": [{"name": "Kim Mata", "email": "kbm2n@virginia.edu"}],
        "section_type": "Laboratory",
        "meetings": [
            {
                "days": "-",
                "start_time": "",
                "end_time": "",
                "start_dt": "08/23/2022",
                "end_dt": "12/06/2022",
                "facility_id": "-",
                "facility_descr": "-",
                "instructor": "Kim Mata",
            }
        ],
        "crse_attr": "CORE",
        "crse_attr_value": "CORE-CRITTHINK,CORE-ORALCOMM,CORE-RESEARCH",
        "reserve_caps": [],
    },
    {
        "index": 5,
        "crse_id": "007226",
        "crse_offer_nbr": 1,
        "strm": "1228",
        "session_code": "1",
        "session_descr": "Regular Academic Session",
        "class_section": "001",
        "location": "MAIN",
        "location_descr": "On Grounds",
        "start_dt": "08/23/2022",
        "end_dt": "12/06/2022",
        "class_stat": "A",
        "campus": "MAIN",
        "campus_descr": "Main Campus",
        "class_nbr": 11750,
        "acad_career": "UGRD",
        "acad_career_descr": "Undergraduate",
        "component": "STO",
        "subject": "DANC",
        "subject_descr": "Dance",
        "catalog_nbr": "3210",
        "class_type": "E",
        "schedule_print": "Y",
        "acad_group": "CGAS",
        "instruction_mode": "P",
        "instruction_mode_descr": "In Person",
        "acad_org": "DRAM",
        "wait_tot": 0,
        "wait_cap": 0,
        "class_capacity": 18,
        "enrollment_total": 14,
        "enrollment_available": 4,
        "descr": "Ballet II",
        "rqmnt_designtn": "",
        "units": "1",
        "combined_section": "N",
        "enrl_stat": "O",
        "enrl_stat_descr": "Open",
        "topic": "",
        "instructors": [{"name": "Kathryn Schetlick", "email": "kbs2d@virginia.edu"}],
        "section_type": "STO",
        "meetings": [
            {
                "days": "MoWe",
                "start_time": "14.00.00.000000-05:00",
                "end_time": "15.30.00.000000-05:00",
                "start_dt": "08/23/2022",
                "end_dt": "12/06/2022",
                "bldg_cd": "MGM",
                "bldg_has_coordinates": True,
                "facility_descr": "Memorial Gymnasium 120-MP",
                "room": "MP1",
                "facility_id": "MGM MP1",
                "instructor": "Kathryn Schetlick",
            }
        ],
        "crse_attr": "NCLC",
        "crse_attr_value": "NCLC-LOWCOST",
        "reserve_caps": [],
    },
    {
        "index": 6,
        "crse_id": "039318",
        "crse_offer_nbr": 1,
        "strm": "1228",
        "session_code": "1",
        "session_descr": "Regular Academic Session",
        "class_section": "001",
        "location": "MAIN",
        "location_descr": "On Grounds",
        "start_dt": "08/23/2022",
        "end_dt": "12/06/2022",
        "class_stat": "A",
        "campus": "MAIN",
        "campus_descr": "Main Campus",
        "class_nbr": 20325,
        "acad_career": "UGRD",
        "acad_career_descr": "Undergraduate",
        "component": "SEM",
        "subject": "DANC",
        "subject_descr": "Dance",
        "catalog_nbr": "3610",
        "class_type": "E",
        "schedule_print": "Y",
        "acad_group": "CGAS",
        "instruction_mode": "P",
        "instruction_mode_descr": "In Person",
        "acad_org": "DRAM",
        "wait_tot": 0,
        "wait_cap": 0,
        "class_capacity": 12,
        "enrollment_total": 6,
        "enrollment_available": 6,
        "descr": "Contact Improvisation",
        "rqmnt_designtn": "",
        "units": "1",
        "combined_section": "N",
        "enrl_stat": "O",
        "enrl_stat_descr": "Open",
        "topic": "",
        "instructors": [{"name": "Emily Wright", "email": "kjd3am@virginia.edu"}],
        "section_type": "SEM",
        "meetings": [
            {
                "days": "MoWe",
                "start_time": "15.45.00.000000-05:00",
                "end_time": "17.00.00.000000-05:00",
                "start_dt": "08/23/2022",
                "end_dt": "12/06/2022",
                "bldg_cd": "MGM",
                "bldg_has_coordinates": True,
                "facility_descr": "Memorial Gymnasium 120-MP",
                "room": "MP1",
                "facility_id": "MGM MP1",
                "instructor": "Emily Wright",
            }
        ],
        "crse_attr": "NCLC",
        "crse_attr_value": "NCLC-LOWCOST",
        "reserve_caps": [],
    },
    {
        "index": 7,
        "crse_id": "039319",
        "crse_offer_nbr": 1,
        "strm": "1228",
        "session_code": "1",
        "session_descr": "Regular Academic Session",
        "class_section": "001",
        "location": "MAIN",
        "location_descr": "On Grounds",
        "start_dt": "08/23/2022",
        "end_dt": "12/06/2022",
        "class_stat": "A",
        "campus": "MAIN",
        "campus_descr": "Main Campus",
        "class_nbr": 12819,
        "acad_career": "UGRD",
        "acad_career_descr": "Undergraduate",
        "component": "STO",
        "subject": "DANC",
        "subject_descr": "Dance",
        "catalog_nbr": "3640",
        "class_type": "E",
        "schedule_print": "Y",
        "acad_group": "CGAS",
        "instruction_mode": "P",
        "instruction_mode_descr": "In Person",
        "acad_org": "DRAM",
        "wait_tot": 0,
        "wait_cap": 0,
        "class_capacity": 10,
        "enrollment_total": 10,
        "enrollment_available": 0,
        "descr": "Screendance",
        "rqmnt_designtn": "",
        "units": "3",
        "combined_section": "N",
        "enrl_stat": "C",
        "enrl_stat_descr": "Closed",
        "topic": "",
        "instructors": [{"name": "Kim Mata", "email": "kbm2n@virginia.edu"}],
        "section_type": "STO",
        "meetings": [
            {
                "days": "TuTh",
                "start_time": "15.30.00.000000-05:00",
                "end_time": "16.45.00.000000-05:00",
                "start_dt": "08/23/2022",
                "end_dt": "12/06/2022",
                "bldg_cd": "DRM",
                "bldg_has_coordinates": True,
                "facility_descr": "Drama Education Bldg B010",
                "room": "B010",
                "facility_id": "DRM B010",
                "instructor": "Kim Mata",
            }
        ],
        "crse_attr": "ASUD",
        "crse_attr_value": "ASUD-AIP",
        "reserve_caps": [],
    },
    {
        "index": 8,
        "crse_id": "007322",
        "crse_offer_nbr": 1,
        "strm": "1228",
        "session_code": "1",
        "session_descr": "Regular Academic Session",
        "class_section": "001",
        "location": "MAIN",
        "location_descr": "On Grounds",
        "start_dt": "08/23/2022",
        "end_dt": "12/06/2022",
        "class_stat": "A",
        "campus": "MAIN",
        "campus_descr": "Main Campus",
        "class_nbr": 12494,
        "acad_career": "UGRD",
        "acad_career_descr": "Undergraduate",
        "component": "IND",
        "subject": "DANC",
        "subject_descr": "Dance",
        "catalog_nbr": "4993",
        "class_type": "E",
        "schedule_print": "Y",
        "acad_group": "CGAS",
        "instruction_mode": "P",
        "instruction_mode_descr": "In Person",
        "acad_org": "DRAM",
        "wait_tot": 0,
        "wait_cap": 0,
        "class_capacity": 5,
        "enrollment_total": 3,
        "enrollment_available": 2,
        "descr": "Independent Study: Dance",
        "rqmnt_designtn": "",
        "units": "1 - 3",
        "combined_section": "N",
        "enrl_stat": "O",
        "enrl_stat_descr": "Open",
        "topic": "",
        "instructors": [{"name": "Kim Mata", "email": "kbm2n@virginia.edu"}],
        "section_type": "IND",
        "meetings": [
            {
                "days": "-",
                "start_time": "",
                "end_time": "",
                "start_dt": "08/23/2022",
                "end_dt": "12/06/2022",
                "facility_id": "-",
                "facility_descr": "-",
                "instructor": "Kim Mata",
            }
        ],
        "crse_attr": "",
        "crse_attr_value": "",
        "reserve_caps": [],
    },
]
